/**
 * Bootstrap Chroma vector DB: normalize data (if needed) and ingest into a collection.
 *
 * Usage:
 *   tsx scripts/bootstrap-chroma.ts [--reset] [--collection=name] [--input=path]
 *
 * Defaults:
 *   CHROMA_URL=http://localhost:8000
 *   CHROMA_COLLECTION=cantolyr_lexicon_v1
 *   INPUT=data/vector/chroma-all.jsonl (generated by normalize-for-chroma.ts)
 */

import { existsSync } from "node:fs";
import { load } from "std/dotenv/mod.ts";
import { ChromaClient } from "chromadb";

function flag(name: string): boolean {
  return Deno.args.some((a) => a === `--${name}`);
}

function kv(name: string): string | undefined {
  const a = Deno.args.find((x) => x.startsWith(`--${name}=`));
  return a ? a.split("=", 2)[1] : undefined;
}

async function runDeno(script: string, args: string[], env: Record<string, string> = {}) {
  const p = new Deno.Command(Deno.execPath(), {
    args: ["run", "-A", script, ...args],
    stdout: "inherit",
    stderr: "inherit",
    env,
  }).spawn();
  const { code } = await p.status;
  if (code !== 0) throw new Error(`deno run ${script} exited ${code}`);
}

async function ensureChromaUp(urlStr: string) {
  try {
    const url = new URL(urlStr);
    const client = new ChromaClient({
      ssl: url.protocol === "https:",
      host: url.hostname,
      port: Number(url.port || (url.protocol === "https:" ? 443 : 8000)),
    });
    await client.heartbeat();
  } catch (e) {
    console.error("❌ Could not reach Chroma. Is it running?");
    console.error("   Try: pnpm vector:up");
    throw e;
  }
}

async function maybeNormalize(inputPath: string) {
  if (existsSync(inputPath)) return;
  console.log(`ℹ️  Missing ${inputPath}. Running normalize-for-chroma…`);
  await runDeno("scripts/normalize-for-chroma.ts", []);
}

async function maybeReset(url: string, collection: string, doReset: boolean) {
  if (!doReset) return;
  console.log("♻️  Resetting target collection before ingest…");
  await runDeno("scripts/reset-chroma.ts", [`--collection=${collection}`], { CHROMA_URL: url });
}

async function ingest(url: string, collection: string, inputPath: string) {
  console.log("⬆️  Ingesting into Chroma…");
  await runDeno("scripts/ingest-chroma.ts", [inputPath, collection], { CHROMA_URL: url });
}

async function main() {
  await load({ export: true });
  const chromaUrl = kv("url") || Deno.env.get("CHROMA_URL") || "http://localhost:8000";
  const collection = kv("collection") || Deno.env.get("CHROMA_COLLECTION") ||
    "cantolyr_lexicon_v1_1024";
  const input = kv("input") || "data/vector/chroma-all.jsonl";
  const doReset = flag("reset") ||
    /^(1|true|yes)$/i.test(String(Deno.env.get("VECTOR_RESET_ON_BOOTSTRAP") || ""));

  console.log(`🔗 Chroma: ${chromaUrl}`);
  console.log(`📚 Collection: ${collection}`);
  console.log(`📄 Input: ${input}`);

  await ensureChromaUp(chromaUrl);
  await maybeNormalize(input);
  await maybeReset(chromaUrl, collection, doReset);
  await ingest(chromaUrl, collection, input);

  console.log("✅ Bootstrap complete.");
}

if (import.meta.main) main();
