#!/usr/bin/env tsx

/**
 * Bootstrap Chroma vector DB: normalize data (if needed) and ingest into a collection.
 *
 * Usage:
 *   tsx scripts/bootstrap-chroma.ts [--reset] [--collection=name] [--input=path]
 *
 * Defaults:
 *   CHROMA_URL=http://localhost:8000
 *   CHROMA_COLLECTION=cantolyr_lexicon_v1
 *   INPUT=data/vector/chroma-all.jsonl (generated by normalize-for-chroma.ts)
 */

import { existsSync } from "fs";
import { spawn } from "child_process";
import { ChromaClient } from "chromadb";
import { loadEnvFile, getOptionalEnv } from "../src/infrastructure/config/env.js";

function flag(name: string): boolean {
	return process.argv.some((a) => a === `--${name}`);
}

function kv(name: string): string | undefined {
	const a = process.argv.find((x) => x.startsWith(`--${name}=`));
	return a ? a.split("=", 2)[1] : undefined;
}

function run(
	cmd: string,
	args: string[],
	env: NodeJS.ProcessEnv = {}
): Promise<void> {
	return new Promise((resolve, reject) => {
		const p = spawn(cmd, args, {
			stdio: "inherit",
			env: { ...process.env, ...env },
		});
		p.on("exit", (code) =>
			code === 0
				? resolve()
				: reject(new Error(`${cmd} ${args.join(" ")} exited ${code}`))
		);
		p.on("error", reject);
	});
}

async function ensureChromaUp(urlStr: string) {
	try {
		const url = new URL(urlStr);
		const client = new ChromaClient({
			ssl: url.protocol === "https:",
			host: url.hostname,
			port: Number(url.port || (url.protocol === "https:" ? 443 : 8000)),
		});
		await client.heartbeat();
	} catch (e) {
		console.error("❌ Could not reach Chroma. Is it running?");
		console.error("   Try: pnpm vector:up");
		throw e;
	}
}

async function maybeNormalize(inputPath: string) {
	if (existsSync(inputPath)) return;
	console.log(`ℹ️  Missing ${inputPath}. Running normalize-for-chroma…`);
	await run("tsx", ["scripts/normalize-for-chroma.ts"]);
}

async function maybeReset(url: string, collection: string, doReset: boolean) {
	if (!doReset) return;
	console.log("♻️  Resetting target collection before ingest…");
	await run("tsx", ["scripts/reset-chroma.ts", `--collection=${collection}`], {
		CHROMA_URL: url,
	});
}

async function ingest(url: string, collection: string, inputPath: string) {
	console.log("⬆️  Ingesting into Chroma…");
	await run("tsx", ["scripts/ingest-chroma.ts", inputPath, collection], {
		CHROMA_URL: url,
	});
}

async function main() {
	loadEnvFile();
	const chromaUrl =
		kv("url") || getOptionalEnv("CHROMA_URL", "http://localhost:8000");
	const collection =
		kv("collection") || getOptionalEnv("CHROMA_COLLECTION", "cantolyr_lexicon_v1_768");
	const input = kv("input") || "data/vector/chroma-all.jsonl";
	const doReset =
		flag("reset") ||
		/^(1|true|yes)$/i.test(String(getOptionalEnv("VECTOR_RESET_ON_BOOTSTRAP", "")));

	console.log(`🔗 Chroma: ${chromaUrl}`);
	console.log(`📚 Collection: ${collection}`);
	console.log(`📄 Input: ${input}`);

	await ensureChromaUp(chromaUrl);
	await maybeNormalize(input);
	await maybeReset(chromaUrl, collection, doReset);
	await ingest(chromaUrl, collection, input);

	console.log("✅ Bootstrap complete.");
}

if (import.meta.url === `file://${process.argv[1]}`) main();
